name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "1.20.1-forge"
    tags-ignore:
      - "**"
    paths:
      - "gradle/**"
      - "**.java"
      - "**.kts"
      - "**.properties"
      - "**/build.yml"
  pull_request:
    branches:
      - "1.20.1-forge"
    paths:
      - "gradle/**"
      - "**.java"
      - "**.kts"
      - "**.properties"
      - "**/build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  redirect:
    uses: AlmostReliable/.github/.github/workflows/build-java17.yml@main
