name: Release

on:
  workflow_dispatch:
    inputs:
      target_version:
        type: string
        required: false
        description: "mod version | empty = next option"
      update_type:
        type: choice
        required: false
        description: "update type"
        default: "minor"
        options:
          - "major"
          - "minor"
          - "patch"
          - "none"
      release_type:
        type: choice
        required: true
        description: "type of release"
        default: "release"
        options:
          - "alpha"
          - "beta"
          - "release"
      debug:
        type: boolean
        required: false
        default: false
        description: "enable debug mode (GitHub only)"

jobs:
  redirect:
    uses: AlmostReliable/.github/.github/workflows/release-java17-ff.yml@main
    secrets: inherit
    with:
      mod_name: "SummoningRituals"
      curseforge_id: "671040"
      modrinth_id: "19smZ71v"
      dependencies: |
        jei(optional){curseforge:238222}{modrinth:u6dRKJwZ}
        rei(optional){curseforge:310111}{modrinth:nfn13YXA}
        kubejs(optional){curseforge:238086}{modrinth:umyGl7zF}
      target_version: ${{ github.event.inputs.target_version }}
      update_type: ${{ github.event.inputs.update_type }}
      release_type: ${{ github.event.inputs.release_type }}
      loaders: "forge"
      debug: ${{ github.event.inputs.debug }}
